# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('yom', models.CharField(max_length=200)),
                ('mom', models.CharField(max_length=200)),
                ('mileage', models.PositiveIntegerField()),
                ('doors_num', models.PositiveSmallIntegerField()),
                ('seats_num', models.PositiveSmallIntegerField()),
                ('gear', models.CharField(max_length=200)),
                ('drive', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=200)),
                ('Acc_Music', models.CharField(max_length=200)),
                ('Acc_Keys', models.CharField(max_length=200)),
                ('Acc_Roof', models.CharField(max_length=200)),
                ('Acc_Seats', models.CharField(max_length=200)),
                ('Acc_Lights', models.CharField(max_length=200)),
            ],
        ),
    ]
