# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyacar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('maxdiscount', models.CharField(max_length=200)),
            ],
        ),
    ]
