# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyacar', '0002_carprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carprice',
            old_name='price',
            new_name='carprice',
        ),
    ]
